### ISSUE TITLE
node.py missing "import json" line

### ISSUE THREAD

**Issue by Thomptronics** [UniversalDevicesInc/udi_python_interface#15]
I believe you need to import json to avoid this error:

  File "/var/polyglot/.local/lib/python3.8/site-packages/udi_interface/node.py", line 169, in toJSON
    NLOGGER.debug(json.dumps(self.__dict__))
NameError: name 'json' is not defined

**Comment by bpaauwe** [comment]
Fixed in version 3.0.34 of the udx_interface.
