### ISSUE TITLE
isy class doesn't work with pyisy version 3.0

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/udi_python_interface#7]
The latest pyisy release, 3.0 is very different in how you use it to connect to the ISY and the interface ISY class no longer works with this version.

**Comment by jimboca** [comment]
Can you just change the requirements to use the latest 2.x version for now?

**Comment by bpaauwe** [comment]
Fixed in version 3.0.17.  Changed the requirement to use version 2.1.1 only

3.0+ versions will require major changes in the interface ISY class and possibly changes to node servers that use this as well.
